# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostacking < Formula
  desc "Git stacking using merge"
  homepage "https://github.com/Bhacaz/gostacking"
  version "0.4.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.4.0/gostacking_Darwin_arm64.tar.gz"
    sha256 "3d6f94ccff89f74849cf826ecf0ba549a5b53db392c0bc807dd479c16ee7be6b"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "gostacking"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.4.0/gostacking_Darwin_x86_64.tar.gz"
    sha256 "b0ddd1603730bdd316fd9e97b7b3cd3f81164be58e34be9748554c7d4bad5a1a"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "gostacking"
    end
  end
end
