# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostacking < Formula
  desc "Git stacking using merge"
  homepage "https://github.com/Bhacaz/gostacking"
  version "0.4.5"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.4.5/gostacking_Darwin_arm64.tar.gz"
    sha256 "8f14dd6a22452658b0d9bff4485cb05c30742c97603e29acad56e2784fdb8eae"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.4.5/gostacking_Darwin_x86_64.tar.gz"
    sha256 "640a719d45bed289674a2827edb54de610976073430d5852d3e2341ede95b45a"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
end
