# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostacking < Formula
  desc "Git stacking using merge"
  homepage "https://github.com/Bhacaz/gostacking"
  version "0.6.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.6.0/gostacking_Darwin_arm64.tar.gz"
    sha256 "94c0324df8905ded5bcdc31cdf9dfaebefba87042080a8b9ae1c0b87d4adbc3b"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.6.0/gostacking_Darwin_x86_64.tar.gz"
    sha256 "31ea1f9d0c2dc6b45e49354442e62f4d0cb4b68aca6bf271138d5893968947a5"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
end
