# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostacking < Formula
  desc "Git stacking using merge"
  homepage "https://github.com/Bhacaz/gostacking"
  version "0.7.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.7.0/gostacking_Darwin_arm64.tar.gz"
    sha256 "5aea0153f83bf42bab662894587c9127db1a7e0e831df23871d2ebb9655e2205"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.7.0/gostacking_Darwin_x86_64.tar.gz"
    sha256 "9542210e10a0b8ac08addbcd6d9cb9ac6481939c3f7ca6869d047711c2c0fe0c"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
end
